/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["AppController_index"];
  };
  "/admins": {
    get: operations["AdminsController_findAll"];
    post: operations["AdminsController_create"];
  };
  "/admins/{id}": {
    get: operations["AdminsController_findOne"];
    delete: operations["AdminsController_remove"];
    patch: operations["AdminsController_update"];
  };
  "/patients": {
    get: operations["PatientsController_findAll"];
    post: operations["PatientsController_create"];
  };
  "/patients/{id}": {
    get: operations["PatientsController_findOne"];
    delete: operations["PatientsController_remove"];
    patch: operations["PatientsController_update"];
  };
  "/patients/ban-patient/{id}": {
    patch: operations["PatientsController_banPatient"];
  };
  "/patients/add-credits/{id}": {
    patch: operations["PatientsController_addCredits"];
  };
  "/patients/unban-patient/{id}": {
    patch: operations["PatientsController_unbanPatient"];
  };
  "/therapists": {
    get: operations["TherapistsController_findAll"];
    post: operations["TherapistsController_create"];
  };
  "/therapists/registration": {
    get: operations["TherapistsController_getAllTherapistRegistration"];
    post: operations["TherapistsController_therapistRegistration"];
  };
  "/therapists/registration/{id}": {
    patch: operations["TherapistsController_updateTherapistRegistration"];
  };
  "/therapists/specializations": {
    get: operations["TherapistsController_getAllSpecializations"];
  };
  "/therapists/{id}": {
    get: operations["TherapistsController_findOne"];
    delete: operations["TherapistsController_remove"];
    patch: operations["TherapistsController_update"];
  };
  "/posts": {
    get: operations["PostsController_findAll"];
    post: operations["PostsController_create"];
  };
  "/posts/{id}": {
    get: operations["PostsController_findOne"];
    delete: operations["PostsController_remove"];
    patch: operations["PostsController_update"];
  };
  "/posts/patient-post/{patientId}": {
    get: operations["PostsController_findPatientPost"];
  };
  "/posts/remove-post/{id}": {
    patch: operations["PostsController_userRemovePost"];
  };
  "/seeds": {
    post: operations["SeedsController_create"];
  };
  "/auth/patient/register": {
    post: operations["AuthController_register"];
  };
  "/auth/patient/login": {
    post: operations["AuthController_patient_login"];
  };
  "/auth/patient/logout": {
    get: operations["AuthController_patient_logout"];
  };
  "/auth/admin/login": {
    post: operations["AuthController_login"];
  };
  "/auth/admin/logout": {
    get: operations["AuthController_logout"];
  };
  "/auth/refresh-token": {
    get: operations["AuthController_refreshToken"];
  };
  "/factories": {
    post: operations["FactoriesController_create"];
  };
  "/appointments": {
    get: operations["AppointmentsController_findAll"];
    post: operations["AppointmentsController_create"];
  };
  "/appointments/{id}": {
    get: operations["AppointmentsController_findOne"];
    delete: operations["AppointmentsController_remove"];
    patch: operations["AppointmentsController_update"];
  };
  "/credential": {
    get: operations["CredentialController_findAll"];
    post: operations["CredentialController_create"];
  };
  "/credential/{id}": {
    get: operations["CredentialController_findOne"];
    delete: operations["CredentialController_remove"];
    patch: operations["CredentialController_update"];
  };
  "/like-posts": {
    get: operations["LikePostsController_findAll"];
  };
  "/like-posts/by-post/{id}": {
    get: operations["LikePostsController_findLikePostByPost"];
  };
  "/like-posts/by-patient/{id}": {
    get: operations["LikePostsController_findLikePostByPatient"];
  };
  "/like-posts/{id}": {
    patch: operations["LikePostsController_update"];
  };
  "/post-photos": {
    get: operations["PostPhotosController_findAll"];
    post: operations["PostPhotosController_create"];
  };
  "/post-photos/{id}": {
    get: operations["PostPhotosController_findOne"];
    delete: operations["PostPhotosController_remove"];
    patch: operations["PostPhotosController_update"];
  };
  "/activities": {
    get: operations["ActivitiesController_findAll"];
    post: operations["ActivitiesController_create"];
  };
  "/activities/{id}": {
    get: operations["ActivitiesController_findOne"];
    delete: operations["ActivitiesController_remove"];
    patch: operations["ActivitiesController_update"];
  };
  "/activity-images": {
    get: operations["ActivityImagesController_findAll"];
    post: operations["ActivityImagesController_create"];
  };
  "/activity-images/{id}": {
    get: operations["ActivityImagesController_findOne"];
    delete: operations["ActivityImagesController_remove"];
    patch: operations["ActivityImagesController_update"];
  };
  "/patient-comments": {
    get: operations["PatientCommentsController_findCommentByPost"];
    post: operations["PatientCommentsController_create"];
  };
  "/patient-comments/all": {
    get: operations["PatientCommentsController_findAll"];
  };
  "/patient-comments/comments-new/{id}": {
    get: operations["PatientCommentsController_findCommentByPostV2"];
  };
  "/patient-comments/{id}": {
    get: operations["PatientCommentsController_findOne"];
    delete: operations["PatientCommentsController_remove"];
    patch: operations["PatientCommentsController_update"];
  };
  "/patient-comments/all-replies/{id}": {
    get: operations["PatientCommentsController_findAllReplies"];
  };
  "/patient-comments/remove-comment/{id}": {
    patch: operations["PatientCommentsController_removePost"];
  };
  "/save-posts": {
    get: operations["SavedPostsController_findAll"];
    post: operations["SavedPostsController_create"];
  };
  "/save-posts/{id}": {
    get: operations["SavedPostsController_findOne"];
    patch: operations["SavedPostsController_update"];
  };
  "/save-posts/patient-saved-posts/{id}": {
    get: operations["SavedPostsController_findPatientSavePost"];
  };
  "/credits": {
    get: operations["CreditsController_findAll"];
    post: operations["CreditsController_create"];
  };
  "/credits/all": {
    get: operations["CreditsController_getAllCredit"];
  };
  "/credits/{id}": {
    get: operations["CreditsController_findOne"];
    delete: operations["CreditsController_remove"];
    patch: operations["CreditsController_update"];
  };
  "/stripe/payment-intent": {
    post: operations["StripeController_create"];
  };
  "/stripe/charges": {
    get: operations["StripeController_getAllCharges"];
  };
  "/stripe/balance": {
    get: operations["StripeController_getBalance"];
  };
  "/stripe/payment-intent/{id}": {
    get: operations["StripeController_findOne"];
  };
  "/stripe/{id}": {
    delete: operations["StripeController_remove"];
    patch: operations["StripeController_update"];
  };
  "/stress-monitor": {
    get: operations["StressMonitorController_findAll"];
    post: operations["StressMonitorController_create"];
  };
  "/stress-monitor/{id}": {
    get: operations["StressMonitorController_findOne"];
  };
  "/stress-monitor/stress-monitor-count/{id}": {
    get: operations["StressMonitorController_findStressMonitorCount"];
  };
  "/mind-checkup": {
    get: operations["MindCheckupController_findAll"];
    post: operations["MindCheckupController_create"];
  };
  "/mind-checkup/{id}": {
    get: operations["MindCheckupController_findOne"];
  };
  "/mind-checkup/checkup-count/{id}": {
    get: operations["MindCheckupController_findCheckupCount"];
  };
  "/therapist-application-photos": {
    get: operations["TherapistApplicationPhotosController_findAll"];
    post: operations["TherapistApplicationPhotosController_create"];
  };
  "/therapist-application-photos/{id}": {
    get: operations["TherapistApplicationPhotosController_findOne"];
    delete: operations["TherapistApplicationPhotosController_remove"];
    patch: operations["TherapistApplicationPhotosController_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateAdminDto: {
      email: string;
      password: string;
    };
    AdminResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      email: string;
      phone_number: string;
      roles: ("patient" | "admin" | "therapist")[];
    };
    UpdateAdminDto: {
      email?: string;
      password?: string;
    };
    CreatePatientDto: {
      credential?: string;
      username?: string;
      gender?: string;
      credits?: number;
      profile_img?: string;
    };
    CredentialResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      email: string;
      password: string;
    };
    PatientResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      email: string;
      username: string;
      phone_number: string;
      /** @enum {string} */
      gender: "male" | "female";
      credits: number;
      roles: ("patient" | "admin" | "therapist")[];
      /** @default false */
      is_deleted: boolean;
      /** @default false */
      is_banned: boolean;
      profile_img: string;
      /** @default 0 */
      stress_monitor_count: number;
      /** @default 0 */
      mind_checkup_count: number;
      credential: components["schemas"]["CredentialResponseDto"];
    };
    PostResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      body: string;
      patient: components["schemas"]["PatientResponseDto"];
      like_count: number;
      save_count: number;
      comment_count: number;
      /** @default false */
      stress_result: boolean;
    };
    RelationalPatientResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      email: string;
      username: string;
      phone_number: string;
      /** @enum {string} */
      gender: "male" | "female";
      credits: number;
      roles: ("patient" | "admin" | "therapist")[];
      /** @default false */
      is_deleted: boolean;
      /** @default false */
      is_banned: boolean;
      profile_img: string;
      /** @default 0 */
      stress_monitor_count: number;
      /** @default 0 */
      mind_checkup_count: number;
      credential: components["schemas"]["CredentialResponseDto"];
      posts: components["schemas"]["PostResponseDto"][];
    };
    UpdatePatientDto: {
      credential?: string;
      username?: string;
      gender?: string;
      credits?: number;
      profile_img?: string;
      is_banned: boolean;
      is_deleted: boolean;
      roles: ("patient" | "admin" | "therapist")[];
    };
    UpdateBalanceDto: {
      credits: number;
    };
    CreateTherapistDto: {
      first_name: string;
      last_name: string;
      bio: string;
      username: string;
      email: string;
      hourly_rate: number;
      phone_number: string;
      specializations: string[];
      /** @enum {string} */
      gender: "male" | "female";
      /**
       * @default [
       *   "therapist"
       * ]
       */
      roles: ("patient" | "admin" | "therapist")[];
      /** @default false */
      is_deleted: boolean;
    };
    TherapistRegistrationDto: {
      first_name: string;
      last_name: string;
      email: string;
      status: string;
      therapistApplicationPhotos: string[];
    };
    TherapistRegistrationReponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      first_name: string;
      last_name: string;
      email: string;
      /** @enum {string} */
      status: "requested" | "accepted" | "rejected";
    };
    TherapistApplicationPhotoResponse: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      filename: string;
      therapist_application: components["schemas"]["TherapistRegistrationReponseDto"];
    };
    RelationalTherapistRegistrationResponse: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      first_name: string;
      last_name: string;
      email: string;
      /** @enum {string} */
      status: "requested" | "accepted" | "rejected";
      therapistApplicationPhotos: components["schemas"]["TherapistApplicationPhotoResponse"][];
    };
    UpdateTherapistRegistration: {
      first_name?: string;
      last_name?: string;
      email?: string;
      status?: string;
      therapistApplicationPhotos?: string[];
    };
    TherapistResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      first_name: string;
      last_name: string;
      bio: string;
      username: string;
      email: string;
      phone_number: string;
      hourly_rate: number;
      specializations: string[];
      /** @enum {string} */
      gender: "male" | "female";
      /** @enum {string} */
      roles: "patient" | "admin" | "therapist";
      is_deleted: boolean;
    };
    UpdateTherapistDto: {
      first_name?: string;
      last_name?: string;
      bio?: string;
      username?: string;
      email?: string;
      hourly_rate?: number;
      phone_number?: string;
      specializations?: string[];
      /** @enum {string} */
      gender?: "male" | "female";
      /**
       * @default [
       *   "therapist"
       * ]
       */
      roles?: ("patient" | "admin" | "therapist")[];
      /** @default false */
      is_deleted?: boolean;
    };
    CreatePostDto: {
      body: string;
      patient: string;
      postPhotos: string[];
    };
    CreatePostResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      body: string;
      patient: string;
      like_count: number;
      comment_count: number;
      save_count: number;
      /** @default false */
      stress_result: boolean;
    };
    PostPhotoResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      filename: string;
      post: components["schemas"]["PostResponseDto"];
    };
    RelationalPostResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      body: string;
      patient: components["schemas"]["PatientResponseDto"];
      like_count: number;
      save_count: number;
      comment_count: number;
      /** @default false */
      stress_result: boolean;
      postPhotos: components["schemas"]["PostPhotoResponseDto"][];
    };
    UpdatePostDto: {
      body: string;
      postPhotos: string[];
      /** @default false */
      is_deleted: boolean;
    };
    RegisterDto: {
      credential?: string;
      username?: string;
      gender?: string;
      credits?: number;
      profile_img?: string;
      email: string;
      password: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
    CreateFactoryDto: {
      /** @default 10 */
      length?: number;
    };
    CreateAppointmentDto: {
      note: string;
      prescriptions: string;
      symptoms: string;
      patient: string;
      therapist: string;
      /** Format: date-time */
      scheduleDate: string;
      status: string;
      start_time: string;
      end_time: string;
      duration: number;
      session_price: number;
    };
    AppointmentResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      note: string;
      prescriptions: string;
      symptoms: string;
      /** Format: date-time */
      scheduleDate: string;
      /** @enum {string} */
      status: "requested" | "scheduled" | "completed" | "rejected";
      patient: components["schemas"]["PatientResponseDto"];
      therapist: components["schemas"]["TherapistResponseDto"];
      start_time: string;
      end_time: string;
      duration: number;
      session_price: number;
    };
    UpdateAppointmentDto: {
      note?: string;
      prescriptions?: string;
      symptoms?: string;
      patient?: string;
      therapist?: string;
      /** Format: date-time */
      scheduleDate?: string;
      status?: string;
      start_time?: string;
      end_time?: string;
      duration?: number;
      session_price?: number;
    };
    CreateCredentialDto: Record<string, never>;
    UpdateCredentialDto: Record<string, never>;
    LikePostResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      patient: string;
      post: components["schemas"]["PostResponseDto"];
      is_like: boolean;
    };
    UpdateLikePostDto: {
      patient?: string;
      post?: string;
    };
    UpdatePostPhotoDto: {
      filename?: string;
      post?: Record<string, never>;
    };
    CreateActivityDto: {
      title: string;
      description: string;
      type: string;
      fitness: string;
      mentalHealth: string;
      socialSkill: string;
      development: string;
      stresslvl: number;
      activityImages: string[];
    };
    ActivityResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      title: string;
      description: string;
      type: string;
      fitness: string;
      mentalHealth: string;
      socialSkill: string;
      development: string;
      stresslvl: number;
      activityImages: string[];
    };
    UpdateActivityDto: {
      title?: string;
      description?: string;
      type?: string;
      fitness?: string;
      mentalHealth?: string;
      socialSkill?: string;
      development?: string;
      stresslvl?: number;
      activityImages?: string[];
    };
    UpdateActivityImageDto: Record<string, never>;
    CreatePatientCommentDto: {
      content: string;
      patient: string;
      post: string;
      parent?: string;
      children?: string[];
    };
    OmitTypeClass: {
      _id: string;
      username: string;
      credits: number;
      profile_img: string;
      /** @default 0 */
      stress_monitor_count: number;
      /** @default 0 */
      mind_checkup_count: number;
      credential: components["schemas"]["CredentialResponseDto"];
    };
    PatientCommentResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      content: string;
      patient: components["schemas"]["OmitTypeClass"];
      /** @default false */
      is_deleted: boolean;
      /** @default 0 */
      reply_count: number;
    };
    NestedPatientCommentResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      content: string;
      patient: components["schemas"]["OmitTypeClass"];
      /** @default false */
      is_deleted: boolean;
      /** @default 0 */
      reply_count: number;
      parent: components["schemas"]["PatientCommentResponseDto"];
      post: string;
    };
    RelationalPatientCommentResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      content: string;
      patient: components["schemas"]["OmitTypeClass"];
      /** @default false */
      is_deleted: boolean;
      /** @default 0 */
      reply_count: number;
      parent: components["schemas"]["PatientCommentResponseDto"];
      post: string;
      children: components["schemas"]["NestedPatientCommentResponseDto"][];
    };
    UpdatePatientCommentDto: {
      content?: string;
      patient?: string;
      post?: string;
      parent?: string;
      children?: string[];
      /** @default false */
      is_deleted: boolean;
    };
    CreateSavedPostDto: {
      patient: string;
      post: string;
    };
    SavePostsResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      patient: string;
      post: components["schemas"]["PostResponseDto"];
      is_saved: boolean;
    };
    UpdateSavedPostDto: {
      patient?: string;
      post?: string;
    };
    CreateCreditDto: {
      title: string;
      points: number;
      price: number;
      discount: number;
      is_visible: boolean;
    };
    CreditReponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      title: string;
      points: number;
      price: number;
      discount: number;
      is_visible: boolean;
    };
    UpdateCreditDto: {
      title?: string;
      points?: number;
      price?: number;
      discount?: number;
      is_visible?: boolean;
    };
    CreateStripeDto: {
      amount: number;
      currency: string;
      credits: number;
      patientId: string;
    };
    UpdateStripeDto: {
      amount?: number;
      currency?: string;
      credits?: number;
      patientId?: string;
    };
    CreateStressMonitorDto: {
      total_score: number;
      patient: string;
    };
    StressMonitorResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      patient: components["schemas"]["PatientResponseDto"];
      total_score: number;
    };
    StressMonitorCountResponseDto: {
      /** @default 0 */
      stressMonitorCount: number;
    };
    CreateMindCheckupDto: {
      patient: string;
      /** @enum {string} */
      Gender: "Female" | "Male";
      /** @enum {string} */
      Occupation: "Corporate" | "Student" | "Business" | "Housewife" | "Others";
      /** @enum {string} */
      self_employed: "No" | "Yes";
      /** @enum {string} */
      family_history: "No" | "Yes";
      /** @enum {string} */
      treatment: "No" | "Yes";
      /** @enum {string} */
      Days_Indoors: "1-14 days" | "Go out Every day" | "More than 2 months" | "15-30 days" | "31-60 days";
      /** @enum {string} */
      Growing_Stress: "No" | "Maybe" | "Yes";
      /** @enum {string} */
      Changes_Habits: "No" | "Maybe" | "Yes";
      /** @enum {string} */
      Mood_Swings: "Medium" | "Low" | "High";
      /** @enum {string} */
      Coping_Struggles: "No" | "Yes";
      /** @enum {string} */
      Work_Interest: "No" | "Maybe" | "Yes";
      /** @enum {string} */
      Social_Weakness: "No" | "Maybe" | "Yes";
      /** @enum {string} */
      mental_health_interview: "No" | "Maybe" | "Yes";
      /** @enum {string} */
      care_options: "Not sure" | "No" | "Yes";
    };
    MindCheckupResponseDto: {
      _id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @enum {string} */
      result: "Yes" | "No" | "Maybe";
      patient: components["schemas"]["PatientResponseDto"];
    };
    CheckupCountResponseDto: {
      checkupCount: number;
    };
    UpdateTherapistApplicationPhotoDto: {
      filename?: string;
      therapist_application?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_index: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AdminResponseDto"][];
        };
      };
    };
  };
  AdminsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAdminDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AdminsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AdminsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAdminDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientsController_findAll: {
    parameters: {
      query?: {
        /** @example 1 */
        page?: number;
        /** @example 10 */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPatientResponseDto"][];
        };
      };
    };
  };
  PatientsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePatientDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PatientsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PatientResponseDto"];
        };
      };
    };
  };
  PatientsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePatientDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientsController_banPatient: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientsController_addCredits: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBalanceDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientsController_unbanPatient: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  TherapistsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TherapistResponseDto"][];
        };
      };
    };
  };
  TherapistsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTherapistDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  TherapistsController_getAllTherapistRegistration: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalTherapistRegistrationResponse"][];
        };
      };
    };
  };
  TherapistsController_therapistRegistration: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TherapistRegistrationDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  TherapistsController_updateTherapistRegistration: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTherapistRegistration"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  TherapistsController_getAllSpecializations: {
    responses: {
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  TherapistsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TherapistResponseDto"];
        };
      };
    };
  };
  TherapistsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  TherapistsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTherapistDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PostsController_findAll: {
    parameters: {
      query?: {
        /** @example 1 */
        page?: number;
        /** @example 10 */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPostResponseDto"][];
        };
      };
    };
  };
  PostsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePostDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CreatePostResponseDto"];
        };
      };
    };
  };
  PostsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPostResponseDto"];
        };
      };
    };
  };
  PostsController_remove: {
    parameters: {
      header: {
        patient_id: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PostsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePostDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PostsController_findPatientPost: {
    parameters: {
      path: {
        patientId: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPostResponseDto"][];
        };
      };
    };
  };
  PostsController_userRemovePost: {
    parameters: {
      header: {
        patient_id: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  SeedsController_create: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_patient_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_patient_logout: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_refreshToken: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  FactoriesController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFactoryDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AppointmentsController_findAll: {
    parameters: {
      query: {
        status: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponseDto"][];
        };
      };
    };
  };
  AppointmentsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAppointmentDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AppointmentsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AppointmentResponseDto"];
        };
      };
    };
  };
  AppointmentsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  AppointmentsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAppointmentDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CredentialController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  CredentialController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCredentialDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  CredentialController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CredentialController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CredentialController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCredentialDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  LikePostsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LikePostResponseDto"][];
        };
      };
    };
  };
  LikePostsController_findLikePostByPost: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LikePostResponseDto"][];
        };
      };
    };
  };
  LikePostsController_findLikePostByPatient: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LikePostResponseDto"][];
        };
      };
    };
  };
  LikePostsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateLikePostDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PostPhotosController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PostPhotoResponseDto"];
        };
      };
    };
  };
  PostPhotosController_create: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PostPhotosController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PostPhotosController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PostPhotosController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePostPhotoDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActivitiesController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ActivityResponseDto"][];
        };
      };
    };
  };
  ActivitiesController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActivityDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ActivitiesController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ActivityResponseDto"];
        };
      };
    };
  };
  ActivitiesController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActivitiesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActivityDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActivityImagesController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActivityImagesController_create: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  ActivityImagesController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActivityImagesController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  ActivityImagesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateActivityImageDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientCommentsController_findCommentByPost: {
    parameters: {
      query?: {
        post?: unknown;
        comment?: unknown;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPatientCommentResponseDto"][];
        };
      };
    };
  };
  PatientCommentsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePatientCommentDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  PatientCommentsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPatientCommentResponseDto"][];
        };
      };
    };
  };
  PatientCommentsController_findCommentByPostV2: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPatientCommentResponseDto"][];
        };
      };
    };
  };
  PatientCommentsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RelationalPatientCommentResponseDto"];
        };
      };
    };
  };
  PatientCommentsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientCommentsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePatientCommentDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientCommentsController_findAllReplies: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  PatientCommentsController_removePost: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  SavedPostsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SavePostsResponseDto"][];
        };
      };
    };
  };
  SavedPostsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSavedPostDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  SavedPostsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SavePostsResponseDto"];
        };
      };
    };
  };
  SavedPostsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSavedPostDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  SavedPostsController_findPatientSavePost: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SavePostsResponseDto"];
        };
      };
    };
  };
  CreditsController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CreditReponseDto"][];
        };
      };
    };
  };
  CreditsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCreditDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  CreditsController_getAllCredit: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CreditReponseDto"][];
        };
      };
    };
  };
  CreditsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CreditReponseDto"];
        };
      };
    };
  };
  CreditsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  CreditsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCreditDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  StripeController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStripeDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  StripeController_getAllCharges: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  StripeController_getBalance: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  StripeController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  StripeController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  StripeController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateStripeDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  StressMonitorController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["StressMonitorResponseDto"][];
        };
      };
    };
  };
  StressMonitorController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateStressMonitorDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  StressMonitorController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["StressMonitorResponseDto"][];
        };
      };
    };
  };
  StressMonitorController_findStressMonitorCount: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["StressMonitorCountResponseDto"];
        };
      };
    };
  };
  MindCheckupController_findAll: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MindCheckupResponseDto"][];
        };
      };
    };
  };
  MindCheckupController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMindCheckupDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  MindCheckupController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MindCheckupResponseDto"][];
        };
      };
    };
  };
  MindCheckupController_findCheckupCount: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CheckupCountResponseDto"];
        };
      };
    };
  };
  TherapistApplicationPhotosController_findAll: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  TherapistApplicationPhotosController_create: {
    requestBody: {
      content: {
        "application/json": string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  TherapistApplicationPhotosController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  TherapistApplicationPhotosController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  TherapistApplicationPhotosController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTherapistApplicationPhotoDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
